# Generated by Django 3.0.8 on 2020-07-31 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CLSBV', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='num_start',
            new_name='num_starts',
        ),
    ]
